// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlutaejnenzwifpdkajn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsdXRhZWpuZW56d2lmcGRrYWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzMwODAsImV4cCI6MjA1ODQwOTA4MH0.Ns4wkqxOk4gVsw9aeus913mzD5Kyl65-cOXBBP2OAFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);